### ISSUE TITLE
Task::unwatch is broken 

### ISSUE THREAD

**Issue by D-Alex** [rock-drivers/drivers-orogen-canbus#2]
The unwatch method is broken in several ways.
- the element is not removed from the vector but the output port is deleted the element is pointing to
- if a mask is used  cached elements might point to a deleted output port because they are not deleted and the method can be used while the component is running.

I am not using the component. I just looked at the code ;-)

**Comment by doudou** [comment]
Fixed by @jrenken 20 days ago ... Thanks for reporting !
